namespace: tp7-kustomize

  # On garde `images:` pour piloter le tag depuis l'overlay (démonstration rollout)
  # Ici on ne change pas le repository, seulement la version (newTag)
images:
- name: ghcr.io/yixuanhuangyx/spring-petclinic
  newName: ghcr.io/yixuanhuangyx/spring-petclinic
  newTag: 4.0.1
- name: spring-petclinic
  newName: ghcr.io/yixuanhuangyx/spring-petclinic
  newTag: 7b4cf871f6ef6e4a4d362a8ac06e4a71beda4423

# Référencer la baseline (réutiliser tous les manifests de base/)
resources:
- ../base

# Appliquer les patches (modifications)
  # Type 1 : JSON Patch (replicas.yaml) - syntaxe très spécifique, ex: /spec/replicas
patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: clinic-deploy
- path: patch-routing.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
